import 'dart:math';

import 'package:my_application/models/billing_model.dart';

const _requestsLimit = 10;

class BillingService {
  var requests = List<Billing>.from([
    {
      "id": 105,
      "amount": 100092.3,
      "paymentMade": null,
      "projectId": 12,
      "vendorId": 6,
      "employeeId": 39,
      "reason": null,
      "status": "Requested",
      "paymentStatus": "Open",
      "orderItems": [
        {
          "id": 116,
          "name": "steel",
          "description": null,
          "price": 10009.23,
          "unit": "Mtr",
          "departmentId": 1,
          "billId": 105,
          "orderId": 83,
          "note": null,
          "quantity": 10,
          "department": null,
          "order": null,
          "bill": {
            "id": 105,
            "amount": 100092.3,
            "paymentMade": null,
            "projectId": 12,
            "vendorId": 6,
            "employeeId": 39,
            "reason": null,
            "status": "Requested",
            "paymentStatus": "Open",
            "orderItems": [],
            "project": {
              "id": 12,
              "clientId": 6,
              "officeId": 15,
              "contractorIds": [],
              "supervisorIds": [],
              "leadIds": [],
              "bankIds": [],
              "technicalHeadId": 39,
              "procurementOfficerId": 39,
              "name": "Godrej Ascend in Dhokali",
              "agreement": null,
              "startDate": "2022-07-01T00:00:00",
              "commencementDate": null,
              "estimateCost": 100,
              "totalCost": null,
              "orderAttachment": null,
              "status": "Active",
              "client": null,
              "office": null,
              "technicalHead": null,
              "procurementOfficer": null,
              "projectItems": [],
              "projectExpenses": [],
              "projectBanks": [],
              "projectLeads": [],
              "projectSupervisors": [],
              "projectContractors": [],
              "photos": [],
              "documents": [],
              "isActive": true,
              "createdBy": 39,
              "createdAt": "2022-07-01T19:40:52.767",
              "updatedBy": 39,
              "updatedAt": "2022-07-01T19:40:52.767"
            },
            "vendor": {
              "id": 6,
              "addressId": 46,
              "businessId": 4,
              "bankId": 70,
              "name": "kailash shinde",
              "contactPerson": "vishal",
              "gst": "JSDJKS832923982",
              "email": "kailash@gmail.com",
              "phone": "9829892389",
              "address": null,
              "bank": null,
              "business": null,
              "isActive": true,
              "createdBy": 39,
              "createdAt": "2022-06-23T15:28:02.367",
              "updatedBy": 39,
              "updatedAt": "2022-07-05T12:47:23.163"
            },
            "employee": {
              "id": 39,
              "userId": null,
              "businessId": 4,
              "code": null,
              "addressId": null,
              "firstName": "vishal",
              "lastName": "chinta",
              "email": "vishalchinta27@gmail.com",
              "mobile": "8355952505",
              "home": null,
              "hourlyRate": null,
              "overtimeRate": null,
              "dob": null,
              "startDate": "2022-06-23T00:00:00",
              "address": null,
              "permissions": [],
              "isActive": true,
              "createdBy": 5,
              "createdAt": "2022-06-23T15:00:15.153",
              "updatedBy": 5,
              "updatedAt": "2022-06-23T15:00:15.153"
            },
            "createdBy": 39,
            "createdAt": "2022-07-08T14:56:00.69",
            "updatedBy": 39,
            "updatedAt": "2022-07-08T14:56:00.69"
          }
        }
      ],
      "project": {
        "id": 12,
        "clientId": 6,
        "officeId": 15,
        "contractorIds": [],
        "supervisorIds": [],
        "leadIds": [],
        "bankIds": [],
        "technicalHeadId": 39,
        "procurementOfficerId": 39,
        "name": "Luxurious 1, 1.5 & 2 BHK Apartments in Vikhroli.",
        "agreement": null,
        "startDate": "2022-07-01T00:00:00",
        "commencementDate": null,
        "estimateCost": 100,
        "totalCost": null,
        "orderAttachment": null,
        "status": "Active",
        "client": null,
        "office": null,
        "technicalHead": null,
        "procurementOfficer": null,
        "projectItems": [],
        "projectExpenses": [],
        "projectBanks": [],
        "projectLeads": [],
        "projectSupervisors": [],
        "projectContractors": [],
        "photos": [],
        "documents": [],
        "isActive": true,
        "createdBy": 39,
        "createdAt": "2022-07-01T19:40:52.767",
        "updatedBy": 39,
        "updatedAt": "2022-07-01T19:40:52.767"
      },
      "vendor": {
        "id": 6,
        "addressId": 46,
        "businessId": 4,
        "bankId": 70,
        "name": "kailash shinde",
        "contactPerson": "vishal",
        "gst": "JSDJKS832923982",
        "email": "kailash@gmail.com",
        "phone": "9829892389",
        "address": null,
        "bank": null,
        "business": null,
        "isActive": true,
        "createdBy": 39,
        "createdAt": "2022-06-23T15:28:02.367",
        "updatedBy": 39,
        "updatedAt": "2022-07-05T12:47:23.163"
      },
      "employee": {
        "id": 39,
        "userId": null,
        "businessId": 4,
        "code": null,
        "addressId": null,
        "firstName": "vishal",
        "lastName": "chinta",
        "email": "vishalchinta27@gmail.com",
        "mobile": "8355952505",
        "home": null,
        "hourlyRate": null,
        "overtimeRate": null,
        "dob": null,
        "startDate": "2022-06-23T00:00:00",
        "address": null,
        "permissions": [],
        "isActive": true,
        "createdBy": 5,
        "createdAt": "2022-06-23T15:00:15.153",
        "updatedBy": 5,
        "updatedAt": "2022-06-23T15:00:15.153"
      },
      "createdBy": 39,
      "createdAt": "2022-07-08T14:56:00.69",
      "updatedBy": 39,
      "updatedAt": "2022-07-08T14:56:00.69"
    },
    {
      "id": 106,
      "amount": 18580,
      "paymentMade": null,
      "projectId": 12,
      "vendorId": 6,
      "employeeId": 39,
      "reason": null,
      "status": "Requested",
      "paymentStatus": "Open",
      "orderItems": [
        {
          "id": 117,
          "name": "glass",
          "description": null,
          "price": 92.9,
          "unit": "Tonne",
          "departmentId": 4,
          "billId": 106,
          "orderId": 83,
          "note": null,
          "quantity": 200,
          "department": null,
          "order": null,
          "bill": {
            "id": 106,
            "amount": 18580,
            "paymentMade": null,
            "projectId": 12,
            "vendorId": 6,
            "employeeId": 39,
            "reason": null,
            "status": "Requested",
            "paymentStatus": "Open",
            "orderItems": [],
            "project": {
              "id": 12,
              "clientId": 6,
              "officeId": 15,
              "contractorIds": [],
              "supervisorIds": [],
              "leadIds": [],
              "bankIds": [],
              "technicalHeadId": 39,
              "procurementOfficerId": 39,
              "name": "Eternia At Kalpataru Parkcity",
              "agreement": null,
              "startDate": "2022-07-01T00:00:00",
              "commencementDate": null,
              "estimateCost": 100,
              "totalCost": null,
              "orderAttachment": null,
              "status": "Active",
              "client": null,
              "office": null,
              "technicalHead": null,
              "procurementOfficer": null,
              "projectItems": [],
              "projectExpenses": [],
              "projectBanks": [],
              "projectLeads": [],
              "projectSupervisors": [],
              "projectContractors": [],
              "photos": [],
              "documents": [],
              "isActive": true,
              "createdBy": 39,
              "createdAt": "2022-07-01T19:40:52.767",
              "updatedBy": 39,
              "updatedAt": "2022-07-01T19:40:52.767"
            },
            "vendor": {
              "id": 6,
              "addressId": 46,
              "businessId": 4,
              "bankId": 70,
              "name": "kailash shinde",
              "contactPerson": "vishal",
              "gst": "JSDJKS832923982",
              "email": "kailash@gmail.com",
              "phone": "9829892389",
              "address": null,
              "bank": null,
              "business": null,
              "isActive": true,
              "createdBy": 39,
              "createdAt": "2022-06-23T15:28:02.367",
              "updatedBy": 39,
              "updatedAt": "2022-07-05T12:47:23.163"
            },
            "employee": {
              "id": 39,
              "userId": null,
              "businessId": 4,
              "code": null,
              "addressId": null,
              "firstName": "vishal",
              "lastName": "chinta",
              "email": "vishalchinta27@gmail.com",
              "mobile": "8355952505",
              "home": null,
              "hourlyRate": null,
              "overtimeRate": null,
              "dob": null,
              "startDate": "2022-06-23T00:00:00",
              "address": null,
              "permissions": [],
              "isActive": true,
              "createdBy": 5,
              "createdAt": "2022-06-23T15:00:15.153",
              "updatedBy": 5,
              "updatedAt": "2022-06-23T15:00:15.153"
            },
            "createdBy": 39,
            "createdAt": "2022-07-08T14:56:00.69",
            "updatedBy": 39,
            "updatedAt": "2022-07-08T14:56:00.69"
          }
        }
      ],
      "project": {
        "id": 12,
        "clientId": 6,
        "officeId": 15,
        "contractorIds": [],
        "supervisorIds": [],
        "leadIds": [],
        "bankIds": [],
        "technicalHeadId": 39,
        "procurementOfficerId": 39,
        "name": "Godrej Ascend in Dhokali",
        "agreement": null,
        "startDate": "2022-07-01T00:00:00",
        "commencementDate": null,
        "estimateCost": 100,
        "totalCost": null,
        "orderAttachment": null,
        "status": "Active",
        "client": null,
        "office": null,
        "technicalHead": null,
        "procurementOfficer": null,
        "projectItems": [],
        "projectExpenses": [],
        "projectBanks": [],
        "projectLeads": [],
        "projectSupervisors": [],
        "projectContractors": [],
        "photos": [],
        "documents": [],
        "isActive": true,
        "createdBy": 39,
        "createdAt": "2022-07-01T19:40:52.767",
        "updatedBy": 39,
        "updatedAt": "2022-07-01T19:40:52.767"
      },
      "vendor": {
        "id": 6,
        "addressId": 46,
        "businessId": 4,
        "bankId": 70,
        "name": "kailash shinde",
        "contactPerson": "vishal",
        "gst": "JSDJKS832923982",
        "email": "kailash@gmail.com",
        "phone": "9829892389",
        "address": null,
        "bank": null,
        "business": null,
        "isActive": true,
        "createdBy": 39,
        "createdAt": "2022-06-23T15:28:02.367",
        "updatedBy": 39,
        "updatedAt": "2022-07-05T12:47:23.163"
      },
      "employee": {
        "id": 39,
        "userId": null,
        "businessId": 4,
        "code": null,
        "addressId": null,
        "firstName": "vishal",
        "lastName": "chinta",
        "email": "vishalchinta27@gmail.com",
        "mobile": "8355952505",
        "home": null,
        "hourlyRate": null,
        "overtimeRate": null,
        "dob": null,
        "startDate": "2022-06-23T00:00:00",
        "address": null,
        "permissions": [],
        "isActive": true,
        "createdBy": 5,
        "createdAt": "2022-06-23T15:00:15.153",
        "updatedBy": 5,
        "updatedAt": "2022-06-23T15:00:15.153"
      },
      "createdBy": 39,
      "createdAt": "2022-07-08T14:56:00.69",
      "updatedBy": 39,
      "updatedAt": "2022-07-08T14:56:00.69"
    },
    {
      "id": 106,
      "amount": 18580,
      "paymentMade": null,
      "projectId": 12,
      "vendorId": 6,
      "employeeId": 39,
      "reason": null,
      "status": "Requested",
      "paymentStatus": "Open",
      "orderItems": [
        {
          "id": 117,
          "name": "glass",
          "description": null,
          "price": 92.9,
          "unit": "Tonne",
          "departmentId": 4,
          "billId": 106,
          "orderId": 83,
          "note": null,
          "quantity": 200,
          "department": null,
          "order": null,
          "bill": {
            "id": 106,
            "amount": 18580,
            "paymentMade": null,
            "projectId": 12,
            "vendorId": 6,
            "employeeId": 39,
            "reason": null,
            "status": "Requested",
            "paymentStatus": "Open",
            "orderItems": [],
            "project": {
              "id": 12,
              "clientId": 6,
              "officeId": 15,
              "contractorIds": [],
              "supervisorIds": [],
              "leadIds": [],
              "bankIds": [],
              "technicalHeadId": 39,
              "procurementOfficerId": 39,
              "name": "Godrej Ascend in Dhokali",
              "agreement": null,
              "startDate": "2022-07-01T00:00:00",
              "commencementDate": null,
              "estimateCost": 100,
              "totalCost": null,
              "orderAttachment": null,
              "status": "Active",
              "client": null,
              "office": null,
              "technicalHead": null,
              "procurementOfficer": null,
              "projectItems": [],
              "projectExpenses": [],
              "projectBanks": [],
              "projectLeads": [],
              "projectSupervisors": [],
              "projectContractors": [],
              "photos": [],
              "documents": [],
              "isActive": true,
              "createdBy": 39,
              "createdAt": "2022-07-01T19:40:52.767",
              "updatedBy": 39,
              "updatedAt": "2022-07-01T19:40:52.767"
            },
            "vendor": {
              "id": 6,
              "addressId": 46,
              "businessId": 4,
              "bankId": 70,
              "name": "kailash shinde",
              "contactPerson": "vishal",
              "gst": "JSDJKS832923982",
              "email": "kailash@gmail.com",
              "phone": "9829892389",
              "address": null,
              "bank": null,
              "business": null,
              "isActive": true,
              "createdBy": 39,
              "createdAt": "2022-06-23T15:28:02.367",
              "updatedBy": 39,
              "updatedAt": "2022-07-05T12:47:23.163"
            },
            "employee": {
              "id": 39,
              "userId": null,
              "businessId": 4,
              "code": null,
              "addressId": null,
              "firstName": "vishal",
              "lastName": "chinta",
              "email": "vishalchinta27@gmail.com",
              "mobile": "8355952505",
              "home": null,
              "hourlyRate": null,
              "overtimeRate": null,
              "dob": null,
              "startDate": "2022-06-23T00:00:00",
              "address": null,
              "permissions": [],
              "isActive": true,
              "createdBy": 5,
              "createdAt": "2022-06-23T15:00:15.153",
              "updatedBy": 5,
              "updatedAt": "2022-06-23T15:00:15.153"
            },
            "createdBy": 39,
            "createdAt": "2022-07-08T14:56:00.69",
            "updatedBy": 39,
            "updatedAt": "2022-07-08T14:56:00.69"
          }
        }
      ],
      "project": {
        "id": 12,
        "clientId": 6,
        "officeId": 15,
        "contractorIds": [],
        "supervisorIds": [],
        "leadIds": [],
        "bankIds": [],
        "technicalHeadId": 39,
        "procurementOfficerId": 39,
        "name": "Godrej Ascend in Dhokali",
        "agreement": null,
        "startDate": "2022-07-01T00:00:00",
        "commencementDate": null,
        "estimateCost": 100,
        "totalCost": null,
        "orderAttachment": null,
        "status": "Active",
        "client": null,
        "office": null,
        "technicalHead": null,
        "procurementOfficer": null,
        "projectItems": [],
        "projectExpenses": [],
        "projectBanks": [],
        "projectLeads": [],
        "projectSupervisors": [],
        "projectContractors": [],
        "photos": [],
        "documents": [],
        "isActive": true,
        "createdBy": 39,
        "createdAt": "2022-07-01T19:40:52.767",
        "updatedBy": 39,
        "updatedAt": "2022-07-01T19:40:52.767"
      },
      "vendor": {
        "id": 6,
        "addressId": 46,
        "businessId": 4,
        "bankId": 70,
        "name": "kailash shinde",
        "contactPerson": "vishal",
        "gst": "JSDJKS832923982",
        "email": "kailash@gmail.com",
        "phone": "9829892389",
        "address": null,
        "bank": null,
        "business": null,
        "isActive": true,
        "createdBy": 39,
        "createdAt": "2022-06-23T15:28:02.367",
        "updatedBy": 39,
        "updatedAt": "2022-07-05T12:47:23.163"
      },
      "employee": {
        "id": 39,
        "userId": null,
        "businessId": 4,
        "code": null,
        "addressId": null,
        "firstName": "vishal",
        "lastName": "chinta",
        "email": "vishalchinta27@gmail.com",
        "mobile": "8355952505",
        "home": null,
        "hourlyRate": null,
        "overtimeRate": null,
        "dob": null,
        "startDate": "2022-06-23T00:00:00",
        "address": null,
        "permissions": [],
        "isActive": true,
        "createdBy": 5,
        "createdAt": "2022-06-23T15:00:15.153",
        "updatedBy": 5,
        "updatedAt": "2022-06-23T15:00:15.153"
      },
      "createdBy": 39,
      "createdAt": "2022-07-08T14:56:00.69",
      "updatedBy": 39,
      "updatedAt": "2022-07-08T14:56:00.69"
    },
    {
      "id": 106,
      "amount": 18580,
      "paymentMade": null,
      "projectId": 12,
      "vendorId": 6,
      "employeeId": 39,
      "reason": null,
      "status": "Requested",
      "paymentStatus": "Open",
      "orderItems": [
        {
          "id": 117,
          "name": "glass",
          "description": null,
          "price": 92.9,
          "unit": "Tonne",
          "departmentId": 4,
          "billId": 106,
          "orderId": 83,
          "note": null,
          "quantity": 200,
          "department": null,
          "order": null,
          "bill": {
            "id": 106,
            "amount": 18580,
            "paymentMade": null,
            "projectId": 12,
            "vendorId": 6,
            "employeeId": 39,
            "reason": null,
            "status": "Requested",
            "paymentStatus": "Open",
            "orderItems": [],
            "project": {
              "id": 12,
              "clientId": 6,
              "officeId": 15,
              "contractorIds": [],
              "supervisorIds": [],
              "leadIds": [],
              "bankIds": [],
              "technicalHeadId": 39,
              "procurementOfficerId": 39,
              "name": "Godrej Ascend in Dhokali",
              "agreement": null,
              "startDate": "2022-07-01T00:00:00",
              "commencementDate": null,
              "estimateCost": 100,
              "totalCost": null,
              "orderAttachment": null,
              "status": "Active",
              "client": null,
              "office": null,
              "technicalHead": null,
              "procurementOfficer": null,
              "projectItems": [],
              "projectExpenses": [],
              "projectBanks": [],
              "projectLeads": [],
              "projectSupervisors": [],
              "projectContractors": [],
              "photos": [],
              "documents": [],
              "isActive": true,
              "createdBy": 39,
              "createdAt": "2022-07-01T19:40:52.767",
              "updatedBy": 39,
              "updatedAt": "2022-07-01T19:40:52.767"
            },
            "vendor": {
              "id": 6,
              "addressId": 46,
              "businessId": 4,
              "bankId": 70,
              "name": "kailash shinde",
              "contactPerson": "vishal",
              "gst": "JSDJKS832923982",
              "email": "kailash@gmail.com",
              "phone": "9829892389",
              "address": null,
              "bank": null,
              "business": null,
              "isActive": true,
              "createdBy": 39,
              "createdAt": "2022-06-23T15:28:02.367",
              "updatedBy": 39,
              "updatedAt": "2022-07-05T12:47:23.163"
            },
            "employee": {
              "id": 39,
              "userId": null,
              "businessId": 4,
              "code": null,
              "addressId": null,
              "firstName": "vishal",
              "lastName": "chinta",
              "email": "vishalchinta27@gmail.com",
              "mobile": "8355952505",
              "home": null,
              "hourlyRate": null,
              "overtimeRate": null,
              "dob": null,
              "startDate": "2022-06-23T00:00:00",
              "address": null,
              "permissions": [],
              "isActive": true,
              "createdBy": 5,
              "createdAt": "2022-06-23T15:00:15.153",
              "updatedBy": 5,
              "updatedAt": "2022-06-23T15:00:15.153"
            },
            "createdBy": 39,
            "createdAt": "2022-07-08T14:56:00.69",
            "updatedBy": 39,
            "updatedAt": "2022-07-08T14:56:00.69"
          }
        }
      ],
      "project": {
        "id": 12,
        "clientId": 6,
        "officeId": 15,
        "contractorIds": [],
        "supervisorIds": [],
        "leadIds": [],
        "bankIds": [],
        "technicalHeadId": 39,
        "procurementOfficerId": 39,
        "name": "Godrej Ascend in Dhokali",
        "agreement": null,
        "startDate": "2022-07-01T00:00:00",
        "commencementDate": null,
        "estimateCost": 100,
        "totalCost": null,
        "orderAttachment": null,
        "status": "Active",
        "client": null,
        "office": null,
        "technicalHead": null,
        "procurementOfficer": null,
        "projectItems": [],
        "projectExpenses": [],
        "projectBanks": [],
        "projectLeads": [],
        "projectSupervisors": [],
        "projectContractors": [],
        "photos": [],
        "documents": [],
        "isActive": true,
        "createdBy": 39,
        "createdAt": "2022-07-01T19:40:52.767",
        "updatedBy": 39,
        "updatedAt": "2022-07-01T19:40:52.767"
      },
      "vendor": {
        "id": 6,
        "addressId": 46,
        "businessId": 4,
        "bankId": 70,
        "name": "kailash shinde",
        "contactPerson": "vishal",
        "gst": "JSDJKS832923982",
        "email": "kailash@gmail.com",
        "phone": "9829892389",
        "address": null,
        "bank": null,
        "business": null,
        "isActive": true,
        "createdBy": 39,
        "createdAt": "2022-06-23T15:28:02.367",
        "updatedBy": 39,
        "updatedAt": "2022-07-05T12:47:23.163"
      },
      "employee": {
        "id": 39,
        "userId": null,
        "businessId": 4,
        "code": null,
        "addressId": null,
        "firstName": "vishal",
        "lastName": "chinta",
        "email": "vishalchinta27@gmail.com",
        "mobile": "8355952505",
        "home": null,
        "hourlyRate": null,
        "overtimeRate": null,
        "dob": null,
        "startDate": "2022-06-23T00:00:00",
        "address": null,
        "permissions": [],
        "isActive": true,
        "createdBy": 5,
        "createdAt": "2022-06-23T15:00:15.153",
        "updatedBy": 5,
        "updatedAt": "2022-06-23T15:00:15.153"
      },
      "createdBy": 39,
      "createdAt": "2022-07-08T14:56:00.69",
      "updatedBy": 39,
      "updatedAt": "2022-07-08T14:56:00.69"
    },
  ].map((e) => Billing.fromJson(e)));

  Future<List<Billing>?> getBilling(int employeeId, String status) async {
    // var rs = await HttpHelper.get(Uri.parse(Billing_REQUEST_ENDPOINT),
    //     bearerToken: currentLogin.token);
    // print(rs.statusCode);
    // if (rs.statusCode == 200) {
    //   var jsonObject = jsonDecode(rs.body);
    //   var requests = List<BillingRequest>.from(
    //       [jsonObject].map((e) => BillingRequest.fromJson(e)));
    if (status == "All") {
      return requests;
    } else {
      return requests.where((e) => e.status == status).toList();
    }
    // }
    // return null;
  }

  Future<List<Billing>> getProcurementApprovals(int employeeId, String status,
      [startIndex = 0]) async {
    // var rs = await HttpHelper.get(Uri.parse(Billing_REQUEST_ENDPOINT),
    //     bearerToken: currentLogin.token);
    // print(rs.statusCode);
    // if (rs.statusCode == 200) {
    //   var jsonObject = jsonDecode(rs.body);
    //   var requests = List<BillingRequest>.from(
    //       [jsonObject].map((e) => BillingRequest.fromJson(e)));
    var approved = requests.where((e) => e.status == status).toList();

    return approved
        .getRange(startIndex, min(approved.length, startIndex + _requestsLimit))
        .toList();
    ;
    // }
    // return null;
  }
}
