import 'dart:convert';
import 'package:my_application/global/global_variables.dart';
import '../../helpers/http_helper.dart';
import '../../models/purchaserequest_model.dart';
import '../bloc_service.dart';

class PurchasesService {
  Future<List<PurchaseRequest>?> getPurchases(int employeeId) async {
    // var rs = await HttpHelper.get(Uri.parse(PURCHASE_REQUEST_ENDPOINT),
    //     bearerToken: currentLogin.token);
    // print(rs.statusCode);
    // if (rs.statusCode == 200) {
    //   var jsonObject = jsonDecode(rs.body);
    //   var requests = List<PurchaseRequest>.from(
    //       [jsonObject].map((e) => PurchaseRequest.fromJson(e)));
    var requests = List<PurchaseRequest>.from([
      {
        "id": 89,
        "orderNo": "2CU2ENW-4/22/2022 5:31:12 PM",
        "name": null,
        "totalAmount": null,
        "deliveryAt": "2022-04-22",
        "note": null,
        "priority": 0,
        "orderStatus": 3,
        "employeeId": 10028,
        "projectId": 60,
        "reason": null,
        "orderItems": [
          {
            "id": 200,
            "name": "new",
            "description": null,
            "price": null,
            "unit": 1,
            "departmentId": null,
            "billId": null,
            "orderId": 89,
            "note": null,
            "quantity": 2.09,
            "department": null,
            "bill": null,
            "checked": false
          },
          {
            "id": 201,
            "name": "test",
            "description": null,
            "price": null,
            "unit": 2,
            "departmentId": null,
            "billId": null,
            "orderId": 89,
            "note": null,
            "quantity": 29.92,
            "department": null,
            "bill": null,
            "checked": false
          }
        ],
        "employee": {
          "id": 10028,
          "userId": null,
          "businessId": 3,
          "code": "888",
          "addressId": null,
          "firstName": "vishal",
          "lastName": "chinta1",
          "email": "vishalch@business.com",
          "mobile": "8355952505",
          "home": "8355952505",
          "hourlyRate": null,
          "overtimeRate": null,
          "dob": "1999-01-01T00:00:00",
          "startDate": "2022-03-15T15:45:16.0514647",
          "address": null,
          "permissions": [],
          "isActive": false,
          "createdBy": 0,
          "createdAt": "2022-03-15T15:45:16.05",
          "updatedBy": 3,
          "updatedAt": "2022-03-31T17:59:50.99"
        },
        "project": {
          "id": 60,
          "clientId": 8,
          "officeId": 5,
          "contractorIds": [],
          "supervisorIds": [],
          "leadIds": [],
          "bankIds": [],
          "technicalHeadId": 10028,
          "procurementOfficerId": 10028,
          "name": "New Project ",
          "agreement": "372387237823",
          "startDate": "2022-03-12T00:00:00",
          "commencementDate": "2022-03-11T00:00:00",
          "estimateCost": 1212787128.71,
          "totalCost": 1000000000.21,
          "orderAttachment": null,
          "status": 1,
          "client": null,
          "office": null,
          "technicalHead": null,
          "procurementOfficer": null,
          "projectItems": [],
          "projectExpenses": [],
          "projectBanks": [],
          "projectLeads": [],
          "projectSupervisors": [],
          "projectContractors": [],
          "photos": [],
          "documents": [],
          "isActive": true,
          "createdBy": 10012,
          "createdAt": "2022-02-25T21:21:53.73",
          "updatedBy": 10042,
          "updatedAt": "2022-04-18T19:56:24.3"
        },
        "createdBy": 10028,
        "createdAt": "2022-04-22T17:31:12",
        "updatedBy": 10028,
        "updatedAt": "2022-04-22T17:32:09.677"
      },
      {
        "id": 90,
        "orderNo": "2CU34ENW-4/22/2022 5:31:12 PM",
        "name": null,
        "totalAmount": null,
        "deliveryAt": "2022-04-23",
        "note": null,
        "priority": 0,
        "orderStatus": 5,
        "employeeId": 10028,
        "projectId": 60,
        "reason": null,
        "orderItems": [
          {
            "id": 210,
            "name": "new",
            "description": null,
            "price": null,
            "unit": 1,
            "departmentId": null,
            "billId": null,
            "orderId": 89,
            "note": null,
            "quantity": 2.09,
            "department": null,
            "bill": null,
            "checked": false
          },
          {
            "id": 203,
            "name": "cement",
            "description": null,
            "price": null,
            "unit": 8,
            "departmentId": null,
            "billId": null,
            "orderId": 90,
            "note": null,
            "quantity": 209.00,
            "department": null,
            "bill": null,
            "checked": false
          }
        ],
        "employee": {
          "id": 10028,
          "userId": null,
          "businessId": 3,
          "code": "888",
          "addressId": null,
          "firstName": "vishal",
          "lastName": "chinta1",
          "email": "vishalch@business.com",
          "mobile": "8355952505",
          "home": "8355952505",
          "hourlyRate": null,
          "overtimeRate": null,
          "dob": "1999-01-01T00:00:00",
          "startDate": "2022-03-15T15:45:16.0514647",
          "address": null,
          "permissions": [],
          "isActive": false,
          "createdBy": 0,
          "createdAt": "2022-03-15T15:45:16.05",
          "updatedBy": 3,
          "updatedAt": "2022-03-31T17:59:50.99"
        },
        "project": {
          "id": 60,
          "clientId": 8,
          "officeId": 5,
          "contractorIds": [],
          "supervisorIds": [],
          "leadIds": [],
          "bankIds": [],
          "technicalHeadId": 10028,
          "procurementOfficerId": 10028,
          "name": "New Project ",
          "agreement": "372387237823",
          "startDate": "2022-03-12T00:00:00",
          "commencementDate": "2022-03-11T00:00:00",
          "estimateCost": 1212787128.71,
          "totalCost": 1000000000.21,
          "orderAttachment": null,
          "status": 1,
          "client": null,
          "office": null,
          "technicalHead": null,
          "procurementOfficer": null,
          "projectItems": [],
          "projectExpenses": [],
          "projectBanks": [],
          "projectLeads": [],
          "projectSupervisors": [],
          "projectContractors": [],
          "photos": [],
          "documents": [],
          "isActive": true,
          "createdBy": 10012,
          "createdAt": "2022-02-25T21:21:53.73",
          "updatedBy": 10042,
          "updatedAt": "2022-04-18T19:56:24.3"
        },
        "createdBy": 10028,
        "createdAt": "2022-04-22T17:31:12",
        "updatedBy": 10028,
        "updatedAt": "2022-04-22T17:32:09.677"
      },
      {
        "id": 90,
        "orderNo": "2CU34ENW-4/22/2022 5:31:12 PM",
        "name": null,
        "totalAmount": null,
        "deliveryAt": "2022-04-23",
        "note": null,
        "priority": 0,
        "orderStatus": 0,
        "employeeId": 10028,
        "projectId": 60,
        "reason": null,
        "orderItems": [
          {
            "id": 210,
            "name": "new",
            "description": null,
            "price": null,
            "unit": 1,
            "departmentId": null,
            "billId": null,
            "orderId": 89,
            "note": null,
            "quantity": 2.09,
            "department": null,
            "bill": null,
            "checked": false
          },
          {
            "id": 203,
            "name": "cement",
            "description": null,
            "price": null,
            "unit": 8,
            "departmentId": null,
            "billId": null,
            "orderId": 90,
            "note": null,
            "quantity": 209.00,
            "department": null,
            "bill": null,
            "checked": false
          }
        ],
        "employee": {
          "id": 10028,
          "userId": null,
          "businessId": 3,
          "code": "888",
          "addressId": null,
          "firstName": "vishal",
          "lastName": "chinta1",
          "email": "vishalch@business.com",
          "mobile": "8355952505",
          "home": "8355952505",
          "hourlyRate": null,
          "overtimeRate": null,
          "dob": "1999-01-01T00:00:00",
          "startDate": "2022-03-15T15:45:16.0514647",
          "address": null,
          "permissions": [],
          "isActive": false,
          "createdBy": 0,
          "createdAt": "2022-03-15T15:45:16.05",
          "updatedBy": 3,
          "updatedAt": "2022-03-31T17:59:50.99"
        },
        "project": {
          "id": 60,
          "clientId": 8,
          "officeId": 5,
          "contractorIds": [],
          "supervisorIds": [],
          "leadIds": [],
          "bankIds": [],
          "technicalHeadId": 10028,
          "procurementOfficerId": 10028,
          "name": "New Project ",
          "agreement": "372387237823",
          "startDate": "2022-03-12T00:00:00",
          "commencementDate": "2022-03-11T00:00:00",
          "estimateCost": 1212787128.71,
          "totalCost": 1000000000.21,
          "orderAttachment": null,
          "status": 1,
          "client": null,
          "office": null,
          "technicalHead": null,
          "procurementOfficer": null,
          "projectItems": [],
          "projectExpenses": [],
          "projectBanks": [],
          "projectLeads": [],
          "projectSupervisors": [],
          "projectContractors": [],
          "photos": [],
          "documents": [],
          "isActive": true,
          "createdBy": 10012,
          "createdAt": "2022-02-25T21:21:53.73",
          "updatedBy": 10042,
          "updatedAt": "2022-04-18T19:56:24.3"
        },
        "createdBy": 10028,
        "createdAt": "2022-04-22T17:31:12",
        "updatedBy": 10028,
        "updatedAt": "2022-04-22T17:32:09.677"
      },
      {
        "id": 90,
        "orderNo": "2CU34ENW-4/22/2022 5:31:12 PM",
        "name": null,
        "totalAmount": null,
        "deliveryAt": "2022-04-23",
        "note": null,
        "priority": 0,
        "orderStatus": 2,
        "employeeId": 10028,
        "projectId": 60,
        "reason": null,
        "orderItems": [
          {
            "id": 210,
            "name": "new",
            "description": null,
            "price": null,
            "unit": 1,
            "departmentId": null,
            "billId": null,
            "orderId": 89,
            "note": null,
            "quantity": 2.09,
            "department": null,
            "bill": null,
            "checked": false
          },
          {
            "id": 203,
            "name": "cement",
            "description": null,
            "price": null,
            "unit": 8,
            "departmentId": null,
            "billId": null,
            "orderId": 90,
            "note": null,
            "quantity": 209.00,
            "department": null,
            "bill": null,
            "checked": false
          }
        ],
        "employee": {
          "id": 10028,
          "userId": null,
          "businessId": 3,
          "code": "888",
          "addressId": null,
          "firstName": "vishal",
          "lastName": "chinta1",
          "email": "vishalch@business.com",
          "mobile": "8355952505",
          "home": "8355952505",
          "hourlyRate": null,
          "overtimeRate": null,
          "dob": "1999-01-01T00:00:00",
          "startDate": "2022-03-15T15:45:16.0514647",
          "address": null,
          "permissions": [],
          "isActive": false,
          "createdBy": 0,
          "createdAt": "2022-03-15T15:45:16.05",
          "updatedBy": 3,
          "updatedAt": "2022-03-31T17:59:50.99"
        },
        "project": {
          "id": 60,
          "clientId": 8,
          "officeId": 5,
          "contractorIds": [],
          "supervisorIds": [],
          "leadIds": [],
          "bankIds": [],
          "technicalHeadId": 10028,
          "procurementOfficerId": 10028,
          "name": "New Project ",
          "agreement": "372387237823",
          "startDate": "2022-03-12T00:00:00",
          "commencementDate": "2022-03-11T00:00:00",
          "estimateCost": 1212787128.71,
          "totalCost": 1000000000.21,
          "orderAttachment": null,
          "status": 1,
          "client": null,
          "office": null,
          "technicalHead": null,
          "procurementOfficer": null,
          "projectItems": [],
          "projectExpenses": [],
          "projectBanks": [],
          "projectLeads": [],
          "projectSupervisors": [],
          "projectContractors": [],
          "photos": [],
          "documents": [],
          "isActive": true,
          "createdBy": 10012,
          "createdAt": "2022-02-25T21:21:53.73",
          "updatedBy": 10042,
          "updatedAt": "2022-04-18T19:56:24.3"
        },
        "createdBy": 10028,
        "createdAt": "2022-04-22T17:31:12",
        "updatedBy": 10028,
        "updatedAt": "2022-04-22T17:32:09.677"
      },
      {
        "id": 90,
        "orderNo": "2CU34ENW-4/22/2022 5:31:12 PM",
        "name": null,
        "totalAmount": null,
        "deliveryAt": "2022-04-23",
        "note": null,
        "priority": 0,
        "orderStatus": 0,
        "employeeId": 10028,
        "projectId": 60,
        "reason": null,
        "orderItems": [
          {
            "id": 210,
            "name": "new",
            "description": null,
            "price": null,
            "unit": 1,
            "departmentId": null,
            "billId": null,
            "orderId": 89,
            "note": null,
            "quantity": 2.09,
            "department": null,
            "bill": null,
            "checked": false
          },
          {
            "id": 203,
            "name": "cement",
            "description": null,
            "price": null,
            "unit": 8,
            "departmentId": null,
            "billId": null,
            "orderId": 90,
            "note": null,
            "quantity": 209.00,
            "department": null,
            "bill": null,
            "checked": false
          }
        ],
        "employee": {
          "id": 10028,
          "userId": null,
          "businessId": 3,
          "code": "888",
          "addressId": null,
          "firstName": "vishal",
          "lastName": "chinta1",
          "email": "vishalch@business.com",
          "mobile": "8355952505",
          "home": "8355952505",
          "hourlyRate": null,
          "overtimeRate": null,
          "dob": "1999-01-01T00:00:00",
          "startDate": "2022-03-15T15:45:16.0514647",
          "address": null,
          "permissions": [],
          "isActive": false,
          "createdBy": 0,
          "createdAt": "2022-03-15T15:45:16.05",
          "updatedBy": 3,
          "updatedAt": "2022-03-31T17:59:50.99"
        },
        "project": {
          "id": 60,
          "clientId": 8,
          "officeId": 5,
          "contractorIds": [],
          "supervisorIds": [],
          "leadIds": [],
          "bankIds": [],
          "technicalHeadId": 10028,
          "procurementOfficerId": 10028,
          "name": "New Project ",
          "agreement": "372387237823",
          "startDate": "2022-03-12T00:00:00",
          "commencementDate": "2022-03-11T00:00:00",
          "estimateCost": 1212787128.71,
          "totalCost": 1000000000.21,
          "orderAttachment": null,
          "status": 1,
          "client": null,
          "office": null,
          "technicalHead": null,
          "procurementOfficer": null,
          "projectItems": [],
          "projectExpenses": [],
          "projectBanks": [],
          "projectLeads": [],
          "projectSupervisors": [],
          "projectContractors": [],
          "photos": [],
          "documents": [],
          "isActive": true,
          "createdBy": 10012,
          "createdAt": "2022-02-25T21:21:53.73",
          "updatedBy": 10042,
          "updatedAt": "2022-04-18T19:56:24.3"
        },
        "createdBy": 10028,
        "createdAt": "2022-04-22T17:31:12",
        "updatedBy": 10028,
        "updatedAt": "2022-04-22T17:32:09.677"
      },
      {
        "id": 90,
        "orderNo": "2CU34ENW-4/22/2022 5:31:12 PM",
        "name": null,
        "totalAmount": null,
        "deliveryAt": "2022-04-23",
        "note": null,
        "priority": 0,
        "orderStatus": 2,
        "employeeId": 10028,
        "projectId": 60,
        "reason": null,
        "orderItems": [
          {
            "id": 210,
            "name": "new",
            "description": null,
            "price": null,
            "unit": 1,
            "departmentId": null,
            "billId": null,
            "orderId": 89,
            "note": null,
            "quantity": 2.09,
            "department": null,
            "bill": null,
            "checked": false
          },
          {
            "id": 203,
            "name": "cement",
            "description": null,
            "price": null,
            "unit": 8,
            "departmentId": null,
            "billId": null,
            "orderId": 90,
            "note": null,
            "quantity": 209.00,
            "department": null,
            "bill": null,
            "checked": false
          }
        ],
        "employee": {
          "id": 10028,
          "userId": null,
          "businessId": 3,
          "code": "888",
          "addressId": null,
          "firstName": "vishal",
          "lastName": "chinta1",
          "email": "vishalch@business.com",
          "mobile": "8355952505",
          "home": "8355952505",
          "hourlyRate": null,
          "overtimeRate": null,
          "dob": "1999-01-01T00:00:00",
          "startDate": "2022-03-15T15:45:16.0514647",
          "address": null,
          "permissions": [],
          "isActive": false,
          "createdBy": 0,
          "createdAt": "2022-03-15T15:45:16.05",
          "updatedBy": 3,
          "updatedAt": "2022-03-31T17:59:50.99"
        },
        "project": {
          "id": 60,
          "clientId": 8,
          "officeId": 5,
          "contractorIds": [],
          "supervisorIds": [],
          "leadIds": [],
          "bankIds": [],
          "technicalHeadId": 10028,
          "procurementOfficerId": 10028,
          "name": "New Project ",
          "agreement": "372387237823",
          "startDate": "2022-03-12T00:00:00",
          "commencementDate": "2022-03-11T00:00:00",
          "estimateCost": 1212787128.71,
          "totalCost": 1000000000.21,
          "orderAttachment": null,
          "status": 1,
          "client": null,
          "office": null,
          "technicalHead": null,
          "procurementOfficer": null,
          "projectItems": [],
          "projectExpenses": [],
          "projectBanks": [],
          "projectLeads": [],
          "projectSupervisors": [],
          "projectContractors": [],
          "photos": [],
          "documents": [],
          "isActive": true,
          "createdBy": 10012,
          "createdAt": "2022-02-25T21:21:53.73",
          "updatedBy": 10042,
          "updatedAt": "2022-04-18T19:56:24.3"
        },
        "createdBy": 10028,
        "createdAt": "2022-04-22T17:31:12",
        "updatedBy": 10028,
        "updatedAt": "2022-04-22T17:32:09.677"
      },
      {
        "id": 90,
        "orderNo": "2CU34ENW-4/22/2022 5:31:12 PM",
        "name": null,
        "totalAmount": null,
        "deliveryAt": "2022-04-23",
        "note": null,
        "priority": 0,
        "orderStatus": 0,
        "employeeId": 10028,
        "projectId": 60,
        "reason": null,
        "orderItems": [
          {
            "id": 210,
            "name": "new",
            "description": null,
            "price": null,
            "unit": 1,
            "departmentId": null,
            "billId": null,
            "orderId": 89,
            "note": null,
            "quantity": 2.09,
            "department": null,
            "bill": null,
            "checked": false
          },
          {
            "id": 203,
            "name": "cement",
            "description": null,
            "price": null,
            "unit": 8,
            "departmentId": null,
            "billId": null,
            "orderId": 90,
            "note": null,
            "quantity": 209.00,
            "department": null,
            "bill": null,
            "checked": false
          }
        ],
        "employee": {
          "id": 10028,
          "userId": null,
          "businessId": 3,
          "code": "888",
          "addressId": null,
          "firstName": "vishal",
          "lastName": "chinta1",
          "email": "vishalch@business.com",
          "mobile": "8355952505",
          "home": "8355952505",
          "hourlyRate": null,
          "overtimeRate": null,
          "dob": "1999-01-01T00:00:00",
          "startDate": "2022-03-15T15:45:16.0514647",
          "address": null,
          "permissions": [],
          "isActive": false,
          "createdBy": 0,
          "createdAt": "2022-03-15T15:45:16.05",
          "updatedBy": 3,
          "updatedAt": "2022-03-31T17:59:50.99"
        },
        "project": {
          "id": 60,
          "clientId": 8,
          "officeId": 5,
          "contractorIds": [],
          "supervisorIds": [],
          "leadIds": [],
          "bankIds": [],
          "technicalHeadId": 10028,
          "procurementOfficerId": 10028,
          "name": "New Project ",
          "agreement": "372387237823",
          "startDate": "2022-03-12T00:00:00",
          "commencementDate": "2022-03-11T00:00:00",
          "estimateCost": 1212787128.71,
          "totalCost": 1000000000.21,
          "orderAttachment": null,
          "status": 1,
          "client": null,
          "office": null,
          "technicalHead": null,
          "procurementOfficer": null,
          "projectItems": [],
          "projectExpenses": [],
          "projectBanks": [],
          "projectLeads": [],
          "projectSupervisors": [],
          "projectContractors": [],
          "photos": [],
          "documents": [],
          "isActive": true,
          "createdBy": 10012,
          "createdAt": "2022-02-25T21:21:53.73",
          "updatedBy": 10042,
          "updatedAt": "2022-04-18T19:56:24.3"
        },
        "createdBy": 10028,
        "createdAt": "2022-04-22T17:31:12",
        "updatedBy": 10028,
        "updatedAt": "2022-04-22T17:32:09.677"
      },
      {
        "id": 90,
        "orderNo": "2CU34ENW-4/22/2022 5:31:12 PM",
        "name": null,
        "totalAmount": null,
        "deliveryAt": "2022-04-23",
        "note": null,
        "priority": 0,
        "orderStatus": 3,
        "employeeId": 10028,
        "projectId": 60,
        "reason": null,
        "orderItems": [
          {
            "id": 210,
            "name": "new",
            "description": null,
            "price": null,
            "unit": 1,
            "departmentId": null,
            "billId": null,
            "orderId": 89,
            "note": null,
            "quantity": 2.09,
            "department": null,
            "bill": null,
            "checked": false
          },
          {
            "id": 203,
            "name": "cement",
            "description": null,
            "price": null,
            "unit": 8,
            "departmentId": null,
            "billId": null,
            "orderId": 90,
            "note": null,
            "quantity": 209.00,
            "department": null,
            "bill": null,
            "checked": false
          }
        ],
        "employee": {
          "id": 10028,
          "userId": null,
          "businessId": 3,
          "code": "888",
          "addressId": null,
          "firstName": "vishal",
          "lastName": "chinta1",
          "email": "vishalch@business.com",
          "mobile": "8355952505",
          "home": "8355952505",
          "hourlyRate": null,
          "overtimeRate": null,
          "dob": "1999-01-01T00:00:00",
          "startDate": "2022-03-15T15:45:16.0514647",
          "address": null,
          "permissions": [],
          "isActive": false,
          "createdBy": 0,
          "createdAt": "2022-03-15T15:45:16.05",
          "updatedBy": 3,
          "updatedAt": "2022-03-31T17:59:50.99"
        },
        "project": {
          "id": 60,
          "clientId": 8,
          "officeId": 5,
          "contractorIds": [],
          "supervisorIds": [],
          "leadIds": [],
          "bankIds": [],
          "technicalHeadId": 10028,
          "procurementOfficerId": 10028,
          "name": "New Project ",
          "agreement": "372387237823",
          "startDate": "2022-03-12T00:00:00",
          "commencementDate": "2022-03-11T00:00:00",
          "estimateCost": 1212787128.71,
          "totalCost": 1000000000.21,
          "orderAttachment": null,
          "status": 1,
          "client": null,
          "office": null,
          "technicalHead": null,
          "procurementOfficer": null,
          "projectItems": [],
          "projectExpenses": [],
          "projectBanks": [],
          "projectLeads": [],
          "projectSupervisors": [],
          "projectContractors": [],
          "photos": [],
          "documents": [],
          "isActive": true,
          "createdBy": 10012,
          "createdAt": "2022-02-25T21:21:53.73",
          "updatedBy": 10042,
          "updatedAt": "2022-04-18T19:56:24.3"
        },
        "createdBy": 10028,
        "createdAt": "2022-04-22T17:31:12",
        "updatedBy": 10028,
        "updatedAt": "2022-04-22T17:32:09.677"
      },
      {
        "id": 90,
        "orderNo": "2CU34ENW-4/22/2022 5:31:12 PM",
        "name": null,
        "totalAmount": null,
        "deliveryAt": "2022-04-23",
        "note": null,
        "priority": 0,
        "orderStatus": 0,
        "employeeId": 10028,
        "projectId": 60,
        "reason": null,
        "orderItems": [
          {
            "id": 210,
            "name": "new",
            "description": null,
            "price": null,
            "unit": 1,
            "departmentId": null,
            "billId": null,
            "orderId": 89,
            "note": null,
            "quantity": 2.09,
            "department": null,
            "bill": null,
            "checked": false
          },
          {
            "id": 203,
            "name": "cement",
            "description": null,
            "price": null,
            "unit": 8,
            "departmentId": null,
            "billId": null,
            "orderId": 90,
            "note": null,
            "quantity": 209.00,
            "department": null,
            "bill": null,
            "checked": false
          }
        ],
        "employee": {
          "id": 10028,
          "userId": null,
          "businessId": 3,
          "code": "888",
          "addressId": null,
          "firstName": "vishal",
          "lastName": "chinta1",
          "email": "vishalch@business.com",
          "mobile": "8355952505",
          "home": "8355952505",
          "hourlyRate": null,
          "overtimeRate": null,
          "dob": "1999-01-01T00:00:00",
          "startDate": "2022-03-15T15:45:16.0514647",
          "address": null,
          "permissions": [],
          "isActive": false,
          "createdBy": 0,
          "createdAt": "2022-03-15T15:45:16.05",
          "updatedBy": 3,
          "updatedAt": "2022-03-31T17:59:50.99"
        },
        "project": {
          "id": 60,
          "clientId": 8,
          "officeId": 5,
          "contractorIds": [],
          "supervisorIds": [],
          "leadIds": [],
          "bankIds": [],
          "technicalHeadId": 10028,
          "procurementOfficerId": 10028,
          "name": "New Project ",
          "agreement": "372387237823",
          "startDate": "2022-03-12T00:00:00",
          "commencementDate": "2022-03-11T00:00:00",
          "estimateCost": 1212787128.71,
          "totalCost": 1000000000.21,
          "orderAttachment": null,
          "status": 1,
          "client": null,
          "office": null,
          "technicalHead": null,
          "procurementOfficer": null,
          "projectItems": [],
          "projectExpenses": [],
          "projectBanks": [],
          "projectLeads": [],
          "projectSupervisors": [],
          "projectContractors": [],
          "photos": [],
          "documents": [],
          "isActive": true,
          "createdBy": 10012,
          "createdAt": "2022-02-25T21:21:53.73",
          "updatedBy": 10042,
          "updatedAt": "2022-04-18T19:56:24.3"
        },
        "createdBy": 10028,
        "createdAt": "2022-04-22T17:31:12",
        "updatedBy": 10028,
        "updatedAt": "2022-04-22T17:32:09.677"
      },
      {
        "id": 90,
        "orderNo": "2CU34ENW-4/22/2022 5:31:12 PM",
        "name": null,
        "totalAmount": null,
        "deliveryAt": "2022-04-23",
        "note": null,
        "priority": 0,
        "orderStatus": 0,
        "employeeId": 10028,
        "projectId": 60,
        "reason": null,
        "orderItems": [
          {
            "id": 210,
            "name": "new",
            "description": null,
            "price": null,
            "unit": 1,
            "departmentId": null,
            "billId": null,
            "orderId": 89,
            "note": null,
            "quantity": 2.09,
            "department": null,
            "bill": null,
            "checked": false
          },
          {
            "id": 203,
            "name": "cement",
            "description": null,
            "price": null,
            "unit": 8,
            "departmentId": null,
            "billId": null,
            "orderId": 90,
            "note": null,
            "quantity": 209.00,
            "department": null,
            "bill": null,
            "checked": false
          }
        ],
        "employee": {
          "id": 10028,
          "userId": null,
          "businessId": 3,
          "code": "888",
          "addressId": null,
          "firstName": "vishal",
          "lastName": "chinta1",
          "email": "vishalch@business.com",
          "mobile": "8355952505",
          "home": "8355952505",
          "hourlyRate": null,
          "overtimeRate": null,
          "dob": "1999-01-01T00:00:00",
          "startDate": "2022-03-15T15:45:16.0514647",
          "address": null,
          "permissions": [],
          "isActive": false,
          "createdBy": 0,
          "createdAt": "2022-03-15T15:45:16.05",
          "updatedBy": 3,
          "updatedAt": "2022-03-31T17:59:50.99"
        },
        "project": {
          "id": 60,
          "clientId": 8,
          "officeId": 5,
          "contractorIds": [],
          "supervisorIds": [],
          "leadIds": [],
          "bankIds": [],
          "technicalHeadId": 10028,
          "procurementOfficerId": 10028,
          "name": "New Project ",
          "agreement": "372387237823",
          "startDate": "2022-03-12T00:00:00",
          "commencementDate": "2022-03-11T00:00:00",
          "estimateCost": 1212787128.71,
          "totalCost": 1000000000.21,
          "orderAttachment": null,
          "status": 1,
          "client": null,
          "office": null,
          "technicalHead": null,
          "procurementOfficer": null,
          "projectItems": [],
          "projectExpenses": [],
          "projectBanks": [],
          "projectLeads": [],
          "projectSupervisors": [],
          "projectContractors": [],
          "photos": [],
          "documents": [],
          "isActive": true,
          "createdBy": 10012,
          "createdAt": "2022-02-25T21:21:53.73",
          "updatedBy": 10042,
          "updatedAt": "2022-04-18T19:56:24.3"
        },
        "createdBy": 10028,
        "createdAt": "2022-04-22T17:31:12",
        "updatedBy": 10028,
        "updatedAt": "2022-04-22T17:32:09.677"
      },
      {
        "id": 90,
        "orderNo": "2CU34ENW-4/22/2022 5:31:12 PM",
        "name": null,
        "totalAmount": null,
        "deliveryAt": "2022-04-23",
        "note": null,
        "priority": 0,
        "orderStatus": 2,
        "employeeId": 10028,
        "projectId": 60,
        "reason": null,
        "orderItems": [
          {
            "id": 210,
            "name": "new",
            "description": null,
            "price": null,
            "unit": 1,
            "departmentId": null,
            "billId": null,
            "orderId": 89,
            "note": null,
            "quantity": 2.09,
            "department": null,
            "bill": null,
            "checked": false
          },
          {
            "id": 203,
            "name": "cement",
            "description": null,
            "price": null,
            "unit": 8,
            "departmentId": null,
            "billId": null,
            "orderId": 90,
            "note": null,
            "quantity": 209.00,
            "department": null,
            "bill": null,
            "checked": false
          }
        ],
        "employee": {
          "id": 10028,
          "userId": null,
          "businessId": 3,
          "code": "888",
          "addressId": null,
          "firstName": "vishal",
          "lastName": "chinta1",
          "email": "vishalch@business.com",
          "mobile": "8355952505",
          "home": "8355952505",
          "hourlyRate": null,
          "overtimeRate": null,
          "dob": "1999-01-01T00:00:00",
          "startDate": "2022-03-15T15:45:16.0514647",
          "address": null,
          "permissions": [],
          "isActive": false,
          "createdBy": 0,
          "createdAt": "2022-03-15T15:45:16.05",
          "updatedBy": 3,
          "updatedAt": "2022-03-31T17:59:50.99"
        },
        "project": {
          "id": 60,
          "clientId": 8,
          "officeId": 5,
          "contractorIds": [],
          "supervisorIds": [],
          "leadIds": [],
          "bankIds": [],
          "technicalHeadId": 10028,
          "procurementOfficerId": 10028,
          "name": "New Project ",
          "agreement": "372387237823",
          "startDate": "2022-03-12T00:00:00",
          "commencementDate": "2022-03-11T00:00:00",
          "estimateCost": 1212787128.71,
          "totalCost": 1000000000.21,
          "orderAttachment": null,
          "status": 1,
          "client": null,
          "office": null,
          "technicalHead": null,
          "procurementOfficer": null,
          "projectItems": [],
          "projectExpenses": [],
          "projectBanks": [],
          "projectLeads": [],
          "projectSupervisors": [],
          "projectContractors": [],
          "photos": [],
          "documents": [],
          "isActive": true,
          "createdBy": 10012,
          "createdAt": "2022-02-25T21:21:53.73",
          "updatedBy": 10042,
          "updatedAt": "2022-04-18T19:56:24.3"
        },
        "createdBy": 10028,
        "createdAt": "2022-04-22T17:31:12",
        "updatedBy": 10028,
        "updatedAt": "2022-04-22T17:32:09.677"
      },
      {
        "id": 90,
        "orderNo": "2CU34ENW-4/22/2022 5:31:12 PM",
        "name": null,
        "totalAmount": null,
        "deliveryAt": "2022-04-23",
        "note": null,
        "priority": 0,
        "orderStatus": 3,
        "employeeId": 10028,
        "projectId": 60,
        "reason": null,
        "orderItems": [
          {
            "id": 210,
            "name": "new",
            "description": null,
            "price": null,
            "unit": 1,
            "departmentId": null,
            "billId": null,
            "orderId": 89,
            "note": null,
            "quantity": 2.09,
            "department": null,
            "bill": null,
            "checked": false
          },
          {
            "id": 203,
            "name": "cement",
            "description": null,
            "price": null,
            "unit": 8,
            "departmentId": null,
            "billId": null,
            "orderId": 90,
            "note": null,
            "quantity": 209.00,
            "department": null,
            "bill": null,
            "checked": false
          }
        ],
        "employee": {
          "id": 10028,
          "userId": null,
          "businessId": 3,
          "code": "888",
          "addressId": null,
          "firstName": "vishal",
          "lastName": "chinta1",
          "email": "vishalch@business.com",
          "mobile": "8355952505",
          "home": "8355952505",
          "hourlyRate": null,
          "overtimeRate": null,
          "dob": "1999-01-01T00:00:00",
          "startDate": "2022-03-15T15:45:16.0514647",
          "address": null,
          "permissions": [],
          "isActive": false,
          "createdBy": 0,
          "createdAt": "2022-03-15T15:45:16.05",
          "updatedBy": 3,
          "updatedAt": "2022-03-31T17:59:50.99"
        },
        "project": {
          "id": 60,
          "clientId": 8,
          "officeId": 5,
          "contractorIds": [],
          "supervisorIds": [],
          "leadIds": [],
          "bankIds": [],
          "technicalHeadId": 10028,
          "procurementOfficerId": 10028,
          "name": "New Project ",
          "agreement": "372387237823",
          "startDate": "2022-03-12T00:00:00",
          "commencementDate": "2022-03-11T00:00:00",
          "estimateCost": 1212787128.71,
          "totalCost": 1000000000.21,
          "orderAttachment": null,
          "status": 1,
          "client": null,
          "office": null,
          "technicalHead": null,
          "procurementOfficer": null,
          "projectItems": [],
          "projectExpenses": [],
          "projectBanks": [],
          "projectLeads": [],
          "projectSupervisors": [],
          "projectContractors": [],
          "photos": [],
          "documents": [],
          "isActive": true,
          "createdBy": 10012,
          "createdAt": "2022-02-25T21:21:53.73",
          "updatedBy": 10042,
          "updatedAt": "2022-04-18T19:56:24.3"
        },
        "createdBy": 10028,
        "createdAt": "2022-04-22T17:31:12",
        "updatedBy": 10028,
        "updatedAt": "2022-04-22T17:32:09.677"
      },
      {
        "id": 90,
        "orderNo": "2CU34ENW-4/22/2022 5:31:12 PM",
        "name": null,
        "totalAmount": null,
        "deliveryAt": "2022-04-23",
        "note": null,
        "priority": 0,
        "orderStatus": 2,
        "employeeId": 10028,
        "projectId": 60,
        "reason": null,
        "orderItems": [
          {
            "id": 210,
            "name": "new",
            "description": null,
            "price": null,
            "unit": 1,
            "departmentId": null,
            "billId": null,
            "orderId": 89,
            "note": null,
            "quantity": 2.09,
            "department": null,
            "bill": null,
            "checked": false
          },
          {
            "id": 203,
            "name": "cement",
            "description": null,
            "price": null,
            "unit": 8,
            "departmentId": null,
            "billId": null,
            "orderId": 90,
            "note": null,
            "quantity": 209.00,
            "department": null,
            "bill": null,
            "checked": false
          }
        ],
        "employee": {
          "id": 10028,
          "userId": null,
          "businessId": 3,
          "code": "888",
          "addressId": null,
          "firstName": "vishal",
          "lastName": "chinta1",
          "email": "vishalch@business.com",
          "mobile": "8355952505",
          "home": "8355952505",
          "hourlyRate": null,
          "overtimeRate": null,
          "dob": "1999-01-01T00:00:00",
          "startDate": "2022-03-15T15:45:16.0514647",
          "address": null,
          "permissions": [],
          "isActive": false,
          "createdBy": 0,
          "createdAt": "2022-03-15T15:45:16.05",
          "updatedBy": 3,
          "updatedAt": "2022-03-31T17:59:50.99"
        },
        "project": {
          "id": 60,
          "clientId": 8,
          "officeId": 5,
          "contractorIds": [],
          "supervisorIds": [],
          "leadIds": [],
          "bankIds": [],
          "technicalHeadId": 10028,
          "procurementOfficerId": 10028,
          "name": "New Project ",
          "agreement": "372387237823",
          "startDate": "2022-03-12T00:00:00",
          "commencementDate": "2022-03-11T00:00:00",
          "estimateCost": 1212787128.71,
          "totalCost": 1000000000.21,
          "orderAttachment": null,
          "status": 1,
          "client": null,
          "office": null,
          "technicalHead": null,
          "procurementOfficer": null,
          "projectItems": [],
          "projectExpenses": [],
          "projectBanks": [],
          "projectLeads": [],
          "projectSupervisors": [],
          "projectContractors": [],
          "photos": [],
          "documents": [],
          "isActive": true,
          "createdBy": 10012,
          "createdAt": "2022-02-25T21:21:53.73",
          "updatedBy": 10042,
          "updatedAt": "2022-04-18T19:56:24.3"
        },
        "createdBy": 10028,
        "createdAt": "2022-04-22T17:31:12",
        "updatedBy": 10028,
        "updatedAt": "2022-04-22T17:32:09.677"
      },
      {
        "id": 90,
        "orderNo": "2CU34ENW-4/22/2022 5:31:12 PM",
        "name": null,
        "totalAmount": null,
        "deliveryAt": "2022-04-23",
        "note": null,
        "priority": 0,
        "orderStatus": 2,
        "employeeId": 10028,
        "projectId": 60,
        "reason": null,
        "orderItems": [
          {
            "id": 210,
            "name": "new",
            "description": null,
            "price": null,
            "unit": 1,
            "departmentId": null,
            "billId": null,
            "orderId": 89,
            "note": null,
            "quantity": 2.09,
            "department": null,
            "bill": null,
            "checked": false
          },
          {
            "id": 203,
            "name": "cement",
            "description": null,
            "price": null,
            "unit": 8,
            "departmentId": null,
            "billId": null,
            "orderId": 90,
            "note": null,
            "quantity": 209.00,
            "department": null,
            "bill": null,
            "checked": false
          }
        ],
        "employee": {
          "id": 10028,
          "userId": null,
          "businessId": 3,
          "code": "888",
          "addressId": null,
          "firstName": "vishal",
          "lastName": "chinta1",
          "email": "vishalch@business.com",
          "mobile": "8355952505",
          "home": "8355952505",
          "hourlyRate": null,
          "overtimeRate": null,
          "dob": "1999-01-01T00:00:00",
          "startDate": "2022-03-15T15:45:16.0514647",
          "address": null,
          "permissions": [],
          "isActive": false,
          "createdBy": 0,
          "createdAt": "2022-03-15T15:45:16.05",
          "updatedBy": 3,
          "updatedAt": "2022-03-31T17:59:50.99"
        },
        "project": {
          "id": 60,
          "clientId": 8,
          "officeId": 5,
          "contractorIds": [],
          "supervisorIds": [],
          "leadIds": [],
          "bankIds": [],
          "technicalHeadId": 10028,
          "procurementOfficerId": 10028,
          "name": "New Project ",
          "agreement": "372387237823",
          "startDate": "2022-03-12T00:00:00",
          "commencementDate": "2022-03-11T00:00:00",
          "estimateCost": 1212787128.71,
          "totalCost": 1000000000.21,
          "orderAttachment": null,
          "status": 1,
          "client": null,
          "office": null,
          "technicalHead": null,
          "procurementOfficer": null,
          "projectItems": [],
          "projectExpenses": [],
          "projectBanks": [],
          "projectLeads": [],
          "projectSupervisors": [],
          "projectContractors": [],
          "photos": [],
          "documents": [],
          "isActive": true,
          "createdBy": 10012,
          "createdAt": "2022-02-25T21:21:53.73",
          "updatedBy": 10042,
          "updatedAt": "2022-04-18T19:56:24.3"
        },
        "createdBy": 10028,
        "createdAt": "2022-04-22T17:31:12",
        "updatedBy": 10028,
        "updatedAt": "2022-04-22T17:32:09.677"
      },
      {
        "id": 90,
        "orderNo": "2CU34ENW-4/22/2022 5:31:12 PM",
        "name": null,
        "totalAmount": null,
        "deliveryAt": "2022-04-23",
        "note": null,
        "priority": 0,
        "orderStatus": 0,
        "employeeId": 10028,
        "projectId": 60,
        "reason": null,
        "orderItems": [
          {
            "id": 210,
            "name": "new",
            "description": null,
            "price": null,
            "unit": 1,
            "departmentId": null,
            "billId": null,
            "orderId": 89,
            "note": null,
            "quantity": 2.09,
            "department": null,
            "bill": null,
            "checked": false
          },
          {
            "id": 203,
            "name": "cement",
            "description": null,
            "price": null,
            "unit": 8,
            "departmentId": null,
            "billId": null,
            "orderId": 90,
            "note": null,
            "quantity": 209.00,
            "department": null,
            "bill": null,
            "checked": false
          }
        ],
        "employee": {
          "id": 10028,
          "userId": null,
          "businessId": 3,
          "code": "888",
          "addressId": null,
          "firstName": "vishal",
          "lastName": "chinta1",
          "email": "vishalch@business.com",
          "mobile": "8355952505",
          "home": "8355952505",
          "hourlyRate": null,
          "overtimeRate": null,
          "dob": "1999-01-01T00:00:00",
          "startDate": "2022-03-15T15:45:16.0514647",
          "address": null,
          "permissions": [],
          "isActive": false,
          "createdBy": 0,
          "createdAt": "2022-03-15T15:45:16.05",
          "updatedBy": 3,
          "updatedAt": "2022-03-31T17:59:50.99"
        },
        "project": {
          "id": 60,
          "clientId": 8,
          "officeId": 5,
          "contractorIds": [],
          "supervisorIds": [],
          "leadIds": [],
          "bankIds": [],
          "technicalHeadId": 10028,
          "procurementOfficerId": 10028,
          "name": "New Project ",
          "agreement": "372387237823",
          "startDate": "2022-03-12T00:00:00",
          "commencementDate": "2022-03-11T00:00:00",
          "estimateCost": 1212787128.71,
          "totalCost": 1000000000.21,
          "orderAttachment": null,
          "status": 1,
          "client": null,
          "office": null,
          "technicalHead": null,
          "procurementOfficer": null,
          "projectItems": [],
          "projectExpenses": [],
          "projectBanks": [],
          "projectLeads": [],
          "projectSupervisors": [],
          "projectContractors": [],
          "photos": [],
          "documents": [],
          "isActive": true,
          "createdBy": 10012,
          "createdAt": "2022-02-25T21:21:53.73",
          "updatedBy": 10042,
          "updatedAt": "2022-04-18T19:56:24.3"
        },
        "createdBy": 10028,
        "createdAt": "2022-04-22T17:31:12",
        "updatedBy": 10028,
        "updatedAt": "2022-04-22T17:32:09.677"
      },
    ].map((e) => PurchaseRequest.fromJson(e)));

    return requests;
    // }
    // return null;
  }
}
